[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "BMY8YvAftXsm6EXDa7FVkny41dDLrMMXzLKagjCaZxq6"

[programs.devnet]
contract = "BMY8YvAftXsm6EXDa7FVkny41dDLrMMXzLKagjCaZxq6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/my-solana-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
